#from planner import db, models
"""
db.create_all()
db.session.commit()
charter = models.Club(name='Charter')
cloister = models.Club(name='Cloister')
colonial = models.Club(name='Colonial')
terrace = models.Club(name='Terrace')
quad = models.Club(name='Quad')
db.session.add(charter)
db.session.add(cloister)
db.session.add(colonial)
db.session.add(terrace)
db.session.add(quad)
db.session.commit()
clubs = models.Club.query.all()
print(clubs)
leilac = models.User(username="leilac", club=terrace)
me = models.User(username="mynetid", club=quad)
db.session.add(leilac)
db.session.add(me)
db.session.commit()"""
